name:                docproc
version:             0.1.0.0
github:              "hugodro/docproc"
license:             BSD3
author:              "Hugo desRosiers"
maintainer:          "hugo.desrosiers@boardingcities.com"
copyright:           "Boarding Cities"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            application

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/hugodro/docproc#readme>

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - bytestring
  - directory
  - text
  - time
  - vector
  - containers
  - unix
  # For YAML (config file):
  - yaml
  - directory
  - filepath
  # For Git (version):
  - gitrev
  # For options:
  - optparse-applicative
  # For Cont(T):
  - mtl
  # For HTTP API:
  - aeson
  - aeson-pretty
  - http-client
  - http-types
  - http-client-tls
  - http-client-multipart
  - http-conduit
  # For JWT crypto support:
  - jose
  - lens
  # For WAI:
  - wai
  - wai-cors
  - wai-extra
  - warp
  - http-media
  # For Servant:
  - servant
  - servant-server
  - servant-auth
  - servant-auth-server
  - servant-multipart
  - streaming-commons
  # For catching errors from Servant:
  - exceptions
  # For SQL:
  - postgresql-binary
  - hasql
  - hasql-th
  - hasql-pool
  - uuid
  # For doc parsing:
  - case-insensitive
  - cmark
  - tagsoup
  - regex-tdfa
  - pandoc
  - pandoc-types
  - doctemplates
  - process
  # For Minio (S3):
  - minio-hs
  - scientific
  - conduit
  - conduit-extra
  - unliftio
  - base64-bytestring
  # For Job Queue:
  - stm
  # For Distributed Computing:
  - distributed-process
  - distributed-process-simplelocalnet
  - binary
  - network-transport-tcp


default-extensions:
- OverloadedStrings
- DuplicateRecordFields
- OverloadedRecordDot


ghc-options:
# - -Wall
# - -Wunused-matches
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
#- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  docproc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - docproc

tests:
  docproc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - docproc
